### ISSUE TITLE
Fundraiser result should be corrected to BTC block 460661 

### ISSUE THREAD

**Issue by mdyring** [cosmos/cosmos.github.io#14]
cosmos.github.io/content/en-US/blog/post-fundraiser.md

This page shows block 460660 as the last accepted BTC contribution block, but AFAIK this was changed to 460661 after the whale adjustment.

Seems important to correct this for posterity but also because some support questions are still popping up on this.

**Comment by nylira** [comment]
Thanks, fixed.
