### ISSUE TITLE
let's consider SSR

### ISSUE THREAD

**Issue by jolesbi** [cosmos/cosmos.github.io#36]
- faster time to content speeds
- better SEO
- eliminate "loading" screen for websites

https://vuejs.org/v2/guide/ssr.html

**Comment by huashengzhang** [comment]
I tried to use ssr, encountered more problems, mainly the internal layout of third-party libraries, of course, there are some other issues

**Comment by huashengzhang** [comment]
HI,I use ssr at https://github.com/huashengzhang/aib-website, look forward your feedback @jolesbi  @nylira

**Comment by nylira** [comment]
Let's not use SSR for now. The flexibility and data-reactivity-ness of client-only is super helpful at this stage of Cosmos.
