### ISSUE TITLE
Suggested modifications of current site

### ISSUE THREAD

**Issue by gamarin2** [cosmos/cosmos.github.io#60]
Hey! Few suggestions to improve current website:

## Sections

- [x] "Introduction" should be replaced by "About". "About" section should be removed or moved to footer
- [x] "About" sub-sections should be: "Introduction, FAQ, Whitepaper" instead of "Overview, FAQ"
- [x]  "Developers" sub-sections should be: "Frameworks, Hackatom" instead of "Overview, Whitepaper, FAQ" (i.e. move "Whitepaper" sub-section to "About" section)

### Add ABCI paragraph

- [x]  ABCI paragraph is missing. Should be just under, or even above, Cosmos-SDK. 
Possible paragraph: 
"The Application-Blockchain Interface (ABCI) allows you to deploy the business logic of your blockchain application in any language. It handles the connexion with the underlying Tendermint engine, which is responsible for the networking and consensus parts of the software. With the ABCI, you can deploy any type of blockchain application - public or private - in no time."
+Add link to Tendermint ABCI doc and ABCI github

### Modifications to Cosmos-SDK section

- [ ] Cosmos SDK -> Cosmos-SDK

> "The Cosmos SDK affords you all the tools you need to rapidly develop robust blockchains and blockchain applications which are interoperable with the Cosmos Hub." 

- [x] Replace with: "The Cosmos-SDK is an ABCI framework written in Golang that affords you..."

>"For example, does your app require fees, how do you want to log messages, do you enable IBC, do you even have a cryptocurrency? In this way, the Cosmos SDK is the "Rails" of cryptocurrencies." 

- [x] Replace with: "It is perfect to build highly-customizable public proof-of-stake blockchains"

## Validator's section

- [x]  Add validator's mailing list subscription box at the bottom. Note: we have to figure it out with @nylira 
- [x]  Update sectioning according to https://github.com/cosmos/cosmos/pull/78 (now merged)
- [x]  Note: this will be replace by "Hub" section eventually. Sub-sections will be: "Staking, Governance, Validators"

## Other

- [x] Replace "Read introduction" from footer with "Read whitepaper"
- Update Introduction sub-section. I will suggest a modified copy soon.

**Comment by gamarin2** [comment]
## Introduction sub-section

### Rephrasing

> Cosmos is a project with an ambitious mission: To create a network of distributed ledgers that will solve long-standing problems in the cryptocurrency and blockchain communities.

Rephrase to: Cosmos is a **network of blockchains** whose purpose it to solve long-standing problems in cryptocurrency and blockchain communities. The end goal is to allow many sovereign and easy-to-develop blockchains to scale and interoperate with each other, creating an Internet of Blockchains.

> Because all inter-zone token transfers go through the Cosmos hub, you can transfer tokens from one zone to another, quickly and securely, without the need for a liquid exchange or a trusted third party between zones.

Rephrase to: Because all inter-zone transfers go through the Cosmos Hub, you can send tokens from one zone to another, quickly and securely, without the need for a liquid exchange or trusted third party between zones.

Also, zones should be Zones and hub should be Hub.

> The Cosmos hub can connect to many different kinds of zones, as long as each zone speaks IBC. As a result, Cosmos can support a variety of currencies and scripting languages like those found in Bitcoin, Ethereum, ZeroCash, CryptoNote, and more.

Rephrase to: The Cosmos Hub can connect to many different kinds of zones - public or private - as long as each zone speaks IBC. Tendermint-based Zones are natively compatible with IBC, but any fast-finality consensus algorithm can be used as a replacement. Cosmos can thus support a wide variety of currencies and scripting languages like those found in Bitcoin, Ethereum, ZeroCash, CryptoNote, and more. Atom is the native token of the Cosmos Hub. It is a license for holders to stake and participate in governance. Learn more about that here (link to staking section).

> Scaling is another open issue for blockchains. Both Ethereum and Bitcoin support only a fraction of the transactions seen daily on payment networks like Visa or Mastercard. In contrast, zones allow Cosmos to scale out indefinitely. If your transaction speed slows in one zone because too many people are using it, you simply add another zone to the hub and direct half the users over that zone, thereby doubling your transaction speed. Meanwhile, the Cosmos hub ensures that any zones connected to it remain in sync.

Rephrase to: Scaling is another open issue for blockchains. Both Ethereum and Bitcoin support only a fraction of the transactions seen daily on payment networks like Visa or Mastercard. In contrast, Tendermint and IBC allow blockchains in Cosmos to scale out indefinitely. Zones built on top of Tendermint can handle up to thousands of transactions per second by themselves. And even if transaction speed slows down on a Zone because too many people are using it, another identical Zone can be added to the Hub and half of the users directed to it, thereby doubling transaction capacity. Meanwhile, the Cosmos Hub ensure that Zones connected to it remain in sync.

### Add section "Developer Friendly"

- Replace section "Upgradeability" by "Developer Friendly"
- Rename sections "Interoperable, Scalable, Developer Friendly, Decentralized"

**Copy for section "Developer Friendly"**

In progress (in 1 hour)

**Comment by jolesbi** [comment]
> "Developers" sub-sections should be: "Frameworks, Hackatom" instead of "Overview, Whitepaper, FAQ"

I prefer Overview, Hackatom. But also, do we have to keep HackAtom there? It is old...

@gamarin2 @nylira ?

**Comment by gamarin2** [comment]
I'm trying to limit the use of "Overview" in website, but I'm not against moving away from "Frameworks". As for HackAtom, should it be replaced by a more general section where we would add Bug Bounty Program infos?

**Comment by kohola71** [comment]
@gamarin2 @jolesbi how about a separate section "Community" (say after Validators, before Team) where we'd put Hackatom info and list community meetups / events info. And maybe swag order option in the future.

**Comment by nylira** [comment]
I'm working on these changes right now. Why 'Cosmos-SDK' instead of 'Cosmos SDK'? I prefer the dash-less version. More people will write it without the dash because it's an uncommon addition.

**Comment by nylira** [comment]
Well, it looks like just about everything is done already. Let's close this and make a new issue if we want to change anything.
