### ISSUE TITLE
Create /team page for cosmos.network

### ISSUE THREAD

**Issue by hcopperm** [cosmos/cosmos.github.io#7]
* link prominently to tendermint.com/about
* cosmos.network/team should show Interchain Foundation // Foundation Council = { Jae, Ethan, Guido } with bios, and list All in Bits, Inc as corporate member and link prominently to tendermint.com/about
And also list as advisors, Ash, Franck, and Thomas, and Don & Alex Tapscott.

and under in "team" it should say "All in Bits, Inc", and list the employees.  And under "advisors" it should show all the advisors

**Comment by hcopperm** [comment]
https://www.google.com/search?q=Franck+Mikulicz&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiktdXo-NbSAhWrq1QKHYQZBPAQ_AUICSgC&biw=1481&bih=873#tbm=isch&q=Franck+Mikulicz+fxch&*&imgrc=N3Iocw69kpCCLM

**Comment by hcopperm** [comment]
@jaekwon i'm gonna need a new bio for you, as yours currently says: 

>>> Jae Kwon created Tendermint to save the world from needlessly wasting electricity to secure distributed ledgers. Along the way he realized that using quorums and cryptography instead of energy and hashing affords many advantages such as speed and scalability.

and this is not correct for listing under 'Interchain Foundation'

**Comment by hcopperm** [comment]
@jaekwon also i need bios and pics for alex and don tapscott

**Comment by nylira** [comment]
This is online now
